// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Crack the Coding Interview",
    url: `${process.env.PUBLIC_URL}/assets/crack the coding interview.png`,
    originalPrice: 49.95,
    salePrice: 14.95,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Atomic Habits",
    url: `${process.env.PUBLIC_URL}/assets/atomic habits.jpg`,
    originalPrice: 39,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Can't Hurt Me",
    url: `${process.env.PUBLIC_URL}/assets/david goggins.jpeg`,
    originalPrice: 29,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Deep Work",
    url: `${process.env.PUBLIC_URL}/assets/deep work.jpeg`,
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
  },
  {
    id: 5,
    title: "The 10X Rule",
    url: `${process.env.PUBLIC_URL}/assets/book-1.jpeg`,
    originalPrice: 32,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "Sell Or Be Sold",
    url: "https://covers.openlibrary.org/b/id/7737110-L.jpg",
    originalPrice: 70,
    salePrice: 12.5,
    rating: 5,
  },
  {
    id: 7,
    title: "Rich Dad Poor Dad",
    url: `${process.env.PUBLIC_URL}/assets/book-3.jpeg`,
    originalPrice: 11,
    salePrice: 10,
    rating: 4,
  },
  {
    id: 8,
    title: "Cashflow Quadrant",
    url: `${process.env.PUBLIC_URL}/assets/book-4.jpeg`,
    originalPrice: 38,
    salePrice: 17.95,
    rating: 4.5,
  },
  {
    id: 9,
    title: "48 Laws of Power Summary",
    url: `${process.env.PUBLIC_URL}/assets/book-5.jpeg`,
    originalPrice: 35,
    salePrice: 19.95,
    rating: 4.5,
  },
  {
    id: 10,
    title: "The 5 Second Rule",
    url: `${process.env.PUBLIC_URL}/assets/book-6.jpeg`,
    originalPrice: 40,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "How to Win Friends & Influence People",
    url: "https://covers.openlibrary.org/b/id/7895280-L.jpg",
    originalPrice: 30,
    salePrice: 20,
    rating: 5,
  },
  {
    id: 12,
    title: "Mastery",
    url: `${process.env.PUBLIC_URL}/assets/book-8.jpeg`,
    originalPrice: 30,
    salePrice: 12.95,
    rating: 4.5,
  },
];